
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.xavier.work.ws.weather;

import javax.jws.WebService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-09-27T00:33:27.488+08:00
 * Generated source version: 3.1.5
 * 
 */

@WebService(
    serviceName = "GlobalWeather",
    portName = "GlobalWeatherHttpGet",
    targetNamespace = "http://www.webserviceX.NET",
    wsdlLocation = "classpath:xsd/globalweather.wsdl",
    endpointInterface = "com.xavier.work.ws.weather.GlobalWeatherHttpGet")
                      
public class GlobalWeatherHttpGetImpl implements GlobalWeatherHttpGet {

    private static final Logger LOG = LoggerFactory.getLogger(GlobalWeatherHttpGetImpl.class);

    /* (non-Javadoc)
     * @see com.xavier.work.ws.weather.GlobalWeatherHttpGet#getWeather(String  cityName ,)String  countryName )*
     */
    public String getWeather(String cityName,String countryName) { 
        LOG.info("Executing operation getWeather");
        System.out.println(cityName);
        System.out.println(countryName);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.xavier.work.ws.weather.GlobalWeatherHttpGet#getCitiesByCountry(String  countryName )*
     */
    public String getCitiesByCountry(String countryName) { 
        LOG.info("Executing operation getCitiesByCountry");
        System.out.println(countryName);
        try {
            String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
